# All target keywords for Reddit thread discovery
# Organized by bucket priority

KEYWORDS = [
    # Bucket 1: Highest Intent (tool/app/software)
    "best sports betting app",
    "best sports betting apps",
    "best sports betting software",
    "best sports betting tool",
    "best sports betting tools",
    "sports betting analytics app",
    "sports betting software reddit",
    "sports betting tools reddit",
    "best app for sports betting research",
    "best betting app for sharp bettors",
    "best app for finding good bets",
    "best sports betting edge app",
    "sports betting calculator app",
    "best odds comparison app",
    "odds comparison app sports betting",
    "line shopping app sports betting",
    "sports betting odds app",
    "betting value finder app",
    "expected value betting app",
    "EV betting app",

    # Bucket 2: Core Concept (+EV / Expected Value)
    "+EV betting",
    "+EV betting app",
    "+EV betting strategy",
    "+EV sports betting",
    "expected value betting",
    "expected value sports betting",
    "EV betting",
    "positive expected value betting",
    "how to find +EV bets",
    "how to calculate EV in sports betting",
    "sports betting expected value calculator",
    "expected value calculator sports betting",
    "best EV betting tool",
    "best +EV betting app",
    "is +EV betting profitable",
    "can +EV betting beat sportsbooks",

    # Bucket 3: Competitor / Alternative Intent
    "OddsJam alternative",
    "OddsJam alternatives",
    "OddsJam vs Optimal Bet",
    "OddsJam review",
    "is OddsJam worth it",
    "OddsJam reddit",
    "best alternative to OddsJam",
    "cheaper alternative to OddsJam",
    "OddsJam for beginners",
    "OddsJam app alternative",
    "Outlier app review",
    "Outlier betting app reddit",
    "Outlier vs OddsJam",
    "Props.cash alternative",
    "Props.cash review",
    "Rithmm review",
    "Rithmm vs OddsJam",
    "Linemate review",
    "WalterPicks review",
    "best sports betting app reddit",
    "best sports betting tools reddit",

    # Bucket 4: Pain-Point / Problem-Aware
    "why do I keep losing sports bets",
    "why am I losing sports betting",
    "can you actually beat sportsbooks",
    "can you make money sports betting",
    "is sports betting profitable",
    "how to become profitable at sports betting",
    "how to win sports betting long term",
    "how to beat sportsbooks long term",
    "profitable sports betting strategy",
    "real sports betting strategy",
    "sports betting strategy that works",
    "best long term sports betting strategy",
    "how sharp bettors make money",
    "how professional sports bettors win",
    "how do sharps bet sports",

    # Bucket 5: Arbitrage Intent
    "arbitrage betting",
    "arbitrage betting app",
    "sports betting arbitrage",
    "arbitrage sports betting app",
    "arbitrage betting software",
    "best arbitrage betting software",
    "best arbitrage betting app",
    "sports betting arb finder",
    "surebet app",
    "sure bet sports betting app",
    "can arbitrage betting still work",
    "is arbitrage betting legal",
    "odds arbitrage tool",

    # Bucket 6: Line Shopping / Odds Comparison
    "line shopping sports betting",
    "line shopping app sports betting",
    "best line shopping app",
    "best odds app sports betting",
    "compare sportsbook odds",
    "compare betting odds app",
    "best sportsbook odds comparison tool",
    "sportsbook odds finder",
    "find best sportsbook odds",
    "sports betting odds screen",
    "sports betting odds scanner",
    "real time odds comparison sports betting",

    # Bucket 7: Reddit-Native variations
    "best sports betting app reddit",
    "best sports betting tools reddit",
    "best sports betting software reddit",
    "best +EV betting app reddit",
    "best arbitrage betting app reddit",
    "sports betting analytics reddit",
    "sports betting tool reddit",
    "sports betting app for sharps reddit",
    "line shopping app reddit",
    "sports betting calculator reddit",
]
